### ISSUE TITLE
AutoMapper obsolete functions

### ISSUE THREAD

**Issue by rfcdejong** [JonPSmith/GenericServices#14]
Currently the EfGenericDtoBase class is using obsolete functions of AutoMapper.

This has changed as of AutoMapper 4.2
https://lostechies.com/jimmybogard/2016/01/21/removing-the-static-api-from-automapper/

And they will be removed in AutoMapper 5.0

**Comment by JonPSmith** [comment]
Hi rfcdejong,

Thanks for pointing that out, as I haven't been keeping up with AutoMapper changes. I think the move away from a static Mapper is great, as static class make Unit Testing really difficult. 

The main problem I see is I hide all the AutoMapper mapping setup deep inside GenericServices, as it makes it easier for developers. I really like the idea of using dependency injection to set up all the mapping. However I haven't used it in GenericServices before, so it would be a big breaking change for people. I need to study the best way to do this. 

Have you any experience or suggestions of how I might go about changing over?

**Comment by rfcdejong** [comment]
I'm sad to say I don't have any experience just yet and I only investigated your GenericServices this week.

**Comment by JonPSmith** [comment]
I have updated GenericServices (see release [V1.0.9](https://github.com/JonPSmith/GenericServices/releases/tag/V1.0.9Release)) to use AutoMapper's now preferred way of setting up mapping.
