### ISSUE TITLE
Mono.Reflection dependency

### ISSUE THREAD

**Issue by fhurta** [JonPSmith/GenericServices#16]
There is unnecessary dependency on Mono.Reflection in GenericServices. Please remove it if there are no plans with it.

**Comment by JonPSmith** [comment]
Hi @fhurta,

I had a look and Mono.Reflections comes from the [DelegateDecomplier](https://github.com/hazzik/DelegateDecompiler) that GenericServices uses to allow `[Computed]` properties to be included in a EF LINQ command.

**Comment by JonPSmith** [comment]
This issue is closed
