### ISSUE TITLE
Not An Issue!!

### ISSUE THREAD

**Issue by ismailyilmaz** [JonPSmith/GenericServices#2]
Sir I just looked through your this perfect implementation of generic services, it helped me alot about imagining of building my own unique generic services. I'm just wondering why you didn't use the Implementation of GenericRepository too? or you think it's anti-pattern? or that implementation was in somewhere in project and i'm missing that? If so, I'm really so sorry with that..
Best Regards and Happy Coding... Respect from Istanbul ,Turkey with the much love of UK..:)

**Comment by JonPSmith** [comment]
Hi @ismailyilmaz. Check out the new documentation, new example web site and the NuGet release of GenericServices. Might be interesting to you.

**Comment by ismailyilmaz** [comment]
Hi dear @JonPSmith ,
Sure I will check it out immediately. I really can't wait to see it, thanks for notifying me..:)
