### ISSUE TITLE
Question: Why does delete expect an entity instead of a DTO?

### ISSUE THREAD

**Issue by Meldinoor** [JonPSmith/GenericServices#21]
When I call ICrudServicesAsync.DeleteAndSaveAsync\<MyDtoType\>(), I get a non-descript error message.
Searching the issues I find reference to how passing DTOs to Delete is not possible #9 but the error message I got was not as specific as the message mentioned in that issue.

The error I got was:
("Property 'Int64 Id' is not defined for type '...MyDtoType...' (Parameter 'property')'")

MyDtoType implements ILinkToEntity\<MyEntityType\>.

I had hoped to be able to avoid using my EF entities at all in my domain logic.

Is there a reason why this isn't supported?

**Comment by JonPSmith** [comment]
Hi @Meldinoor,

The signature of the DeleteAndSave method is `ISuccessOrErrors Delete<TEntity>( param object [] keys)`. The idea is you give the **entity class** you want to delete and the primary key(s) of the entry you want to delete.

Have a look at the documentation in the Wiki - see [DeleteService](https://github.com/JonPSmith/GenericServices/wiki/DeleteService) for an explanation and all the method signatures.
