### ISSUE TITLE
Question regarding the service layer and DDD

### ISSUE THREAD

**Issue by riffrack** [JonPSmith/GenericServices#5]
Hi Jon

In an [article by Martin Fowler] (http://www.martinfowler.com/bliki/AnemicDomainModel.html) he mentions the following: "This (service) layer is kept thin. It does not contain business rules or knowledge, but only coordinates tasks and delegates work to collaborations of domain objects in the next layer down." 

In your [SampleWebApp] (https://github.com/JonPSmith/SampleMvcWebApp) which uses the GenericServices, the concrete classes and dto classes replicate some domain logic, like [Required] or [MinLength]. Is there any way to hold this centrally within the concrete classes and not duplicate this kind of logic. 

What do you think about this?

Cheers
Jonathan

**Comment by JonPSmith** [comment]
Hi @riffrack,

Good question. I agree with Martin Fowler, who I like a lot. GenericServices aims to be an adapter and facard with no business logic. However if we use DTOs, which hide some of the validation in the data classes, what do you do? 

You could leave out the Validation from the DTO and rely on the validation in the data layer. Problem is you lose browser level validation, which would really hurt the user experience of live error feedback. While having validation in the Service Layer breaks the rules I think putting validation in the DTOs is acceptable. Validation is a bit like Security in that it is a cross-cutting problem.

I would also like to point out that MVC's answer to this is to put the validation in the Presentation layer with ViewModels, which I think is even worse that being in the ServiceLayer. With GenericServices I am trying to make the MVC layer just about presentation, although some business logic creeps in, especially in JavaScript, if you want to provide a first class user experience.
