### ISSUE TITLE
Question regarding the IDeleteService & delete confirmation

### ISSUE THREAD

**Issue by riffrack** [JonPSmith/GenericServices#6]
Hi Jon

How you would implement the delete confirmation. The default ASP.NET scaffolding adds a delete confirmation page. You must have a reason for omiting this page. Would you just create a client side confirmation? I couldn't find a way to create a HttpPost controller method using the IDeleteService.

Regards
Jonathan

**Comment by JonPSmith** [comment]
Hi @riffrack,

SampleMvcWebApp is a really basic example and I skipped some issues, like delete confirm. 

In the most of my web sites I use [Kendo UI](http://www.telerik.com/kendo-ui) and also a lot more Ajax forms/feedback. Kendo UI delete from a grid includes a confirm, albeit just a 'confirm' box which isn't that visually nice. The complex example [SampleMvcWebAppComplex](http://complex.samplemvcwebapp.net/) uses Kendo UI and delete is confirmed. Try deleting a pending order.

If you want to write your own then I would suggest say a bit of JavaScript to put up a confirm box, or for a nicer looking version a modal window, with Confirm/Delete buttons. The best way is to deal with the Confirm is to submit a form, as you can then use `[ValidateAntiForgeryToken]` to make the action more secure.
